apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: gamewall
  labels:
    app: gamewall
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/MrMEEE/SquaresGameWall.git
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: gamewall:latest
  triggers:
    - type: ConfigChange
